name: Build and Push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Test checkout
      uses: actions/checkout@v4

    - name: Fetch the latest Bookwyrm release tag
      id: bookwyrm_release
      run: |
        LATEST_RELEASE=$(curl -s "https://api.github.com/repos/bookwyrm-social/bookwyrm/tags" | jq -r '.[0].name')
        echo "Latest release tag is $LATEST_RELEASE"
        echo "::set-output name=tag::$LATEST_RELEASE"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check out Bookwyrm repository at the latest tag
      uses: actions/checkout@v4
      with:
        repository: bookwyrm-social/bookwyrm
        ref: ${{ steps.bookwyrm_release.outputs.tag }}
        path: "bookwyrm"

    - name: Copy our Dockerfile into Bookwyrm context
      run: cp Dockerfile bookwyrm/Dockerfile

    - name: Have database connections open for an hour, instead of opening a new one for each request.
      run: |
        echo 'CONN_MAX_AGE=3600' >> bookwyrm/bookwyrm/settings.py

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: ./bookwyrm
        file: ./bookwyrm/Dockerfile
        push: true
        tags: jrasanen/bookwyrm:${{ steps.bookwyrm_release.outputs.tag }}
        platforms: linux/amd64,linux/arm64
